// NOTE(): PLAYER
#define ENABLE_DIAGONAL_MOVEMENT true

// NOTE(): TURN SYTEM
#define BYPASS_RANDOM_CHANCE true
#define TURN_SPEED_NORMAL 5.0f
#define TURN_SPEED_FAST 10.0
#define ENABLE_TURN_SYSTEM_DEBUG_LOGS false
#define ENEMY_DEBUG_RANGE 6

// NOTE(): RENDERING
#define TILE_PIXEL_SIZE 32
#define SKY_COLOR RGB(59, 44, 81)
#define RENDER_TILE_BITMAPS true

// NOTE(): DEBUG
#define LOG_MESSAGE_LIFETIME 5.0
#define ENABLE_DEBUG_PATHFINDING true

// NOTE(): GAME
#define BASE_HIT_CHANCE 50
#define MELEE_BONUS 15
#define GRAZE_THRESHOLD 10
#define MAX_EFFECTIVE_RANGE 3
#define DISTANCE_PENALTY_PER_TILE 9
#define CRITICAL_HIT_CHANCE 10
#define CRITICAL_DAMAGE_MULTIPLIER 2

#define MAX_SLIME_ACTION_POINTS 10
#define MAX_SLIME_MOVEMENT_POINTS 10
#define MAX_PLAYER_ACTION_POINTS 4
#define MAX_PLAYER_MOVEMENT_POINTS 4