#define ENTITY_SIZE 70
#define ENTITY_PIXEL_HEIGHT 150
#define TILE_PIXEL_SIZE 100

#define ENABLE_DIAGONAL_MOVEMENT true

#define DISABLE_ALL_DEBUG_RENDERING false // TODO(): To be implemented...

#define TURN_SPEED_NORMAL 1.0
#define TURN_SPEED_FAST 5.0