// NOTE(): PLAYER
#define ENABLE_DIAGONAL_MOVEMENT true

// NOTE(): TURN SYTEM
#define BYPASS_RANDOM_CHANCE true
#define TURN_SPEED_NORMAL 5.0f
#define TURN_SPEED_FAST 10.0
#define ENABLE_TURN_SYSTEM_DEBUG_LOGS false
#define ENEMY_DEBUG_RANGE 6

// NOTE(): RENDERING
#define TILE_PIXEL_SIZE 32
#define SKY_COLOR RGB(59, 44, 81)
#define RENDER_TILE_BITMAPS true
#define VIEWPORT_INTEGER_SCALE 4 // 1, 2, 3,

// NOTE(): DEBUG
#define LOG_MESSAGE_LIFETIME 5.0
#define ENABLE_DEBUG_PATHFINDING true